NUM_OF_TOPICS = 4
NUM_OF_ITER = 10

TOTAL_MOVIES = 7000
API_PAGE_FILE_NAME = "api_page.txt"


PROB_OF_LDA = [
    #horror movies
    (0, '0.017*"horror" + 0.017*"zombie" + 0.011*"romance" + 0.009*"angeles" + 0.009*"los" + 0.008*"japan" + 0.007*"death" + 0.007*"school" + 0.007*"story" + 0.007*"anime"'), 
    #police action movies
    (1, '0.012*"murder" + 0.012*"robot" + 0.011*"cop" + 0.011*"police" + 0.010*"york" + 0.010*"city" + 0.010*"sex" + 0.009*"station" + 0.008*"professor" + 0.007*"art"'), 
    #world war 2
    (2, '0.053*"war" + 0.032*"world" + 0.013*"story" + 0.012*"ii" + 0.010*"relationship" + 0.010*"book" + 0.008*"novel" + 0.008*"camp" + 0.008*"concentration" + 0.008*"music"'), 
    #romantic movies
    (3, '0.033*"relationship" + 0.029*"wife" + 0.027*"husband" + 0.013*"murder" + 0.013*"car" + 0.012*"drug" + 0.012*"politics" + 0.006*"money" + 0.006*"comedy" + 0.005*"biography"'), 
    #biography movies
    (4, '0.047*"book" + 0.044*"novel" + 0.019*"story" + 0.019*"biography" + 0.012*"century" + 0.012*"family" + 0.008*"london" + 0.008*"car" + 0.008*"relationship" + 0.007*"race"'), 
    #action movies
    (5, '0.011*"attack" + 0.011*"monster" + 0.011*"revenge" + 0.010*"horror" + 0.010*"island" + 0.009*"prison" + 0.008*"army" + 0.008*"ballet" + 0.008*"creature" + 0.007*"police"'), 
    #family movies
    (6, '0.044*"relationship" + 0.033*"woman" + 0.027*"director" + 0.020*"mother" + 0.018*"daughter" + 0.015*"sister" + 0.012*"murder" + 0.011*"book" + 0.010*"novel" + 0.009*"son"'), 
    #history movies
    (7, '0.016*"history" + 0.014*"century" + 0.010*"school" + 0.010*"music" + 0.008*"time" + 0.008*"france" + 0.008*"biography" + 0.007*"murder" + 0.007*"christmas" + 0.007*"movie"'), 
    #lgbt movies
    (8, '0.029*"gay" + 0.023*"relationship" + 0.017*"child" + 0.016*"lgbt" + 0.010*"movie" + 0.010*"murder" + 0.010*"family" + 0.009*"killer" + 0.008*"age" + 0.008*"century"'), 
    #drugs movies
    (9, '0.021*"drug" + 0.015*"woman" + 0.012*"director" + 0.011*"age" + 0.010*"family" + 0.010*"murder" + 0.008*"relationship" + 0.008*"story" + 0.008*"soccer" + 0.008*"football"')
]

TOPICS_OF_LDA = [("'71", 5), ('12 Feet Deep', 6), ('13 Graves', 3), ('1917', 2), 
    ('1945: The Savage Peace', 2), ('2 Guns', 3), ('2.0', 1),
    ('21 Bridges', 6), ('28 Weeks Later', 7), ('3 from Hell', 6), 
    ('4 latas', 8), ('40 Minutes Over Maui', 8), ('47 Meters Down', 5), 
    ('47 Meters Down: Uncaged', 0), ('5 Centimeters per Second', 2),
    ('522. A Cat, a Chinese Guy and My Father', 1), ('55 Steps', 4), 
    ('7 Days in Entebbe', 9), ('8½', 0), ('A Beautiful Day in the Neighborhood', 4),
    ('A Christmas Carol', 4), ('A Dark Place', 7), ('A Dark Song', 8), 
    ("A Dog's Journey", 4), ("A Dog's Way Home", 4), ('A Dose of Happiness', 9), 
    ('A Fistful of Lead', 8), ('A Mermaid for Christmas', 6), ('A Million Little Pieces', 9), 
    ('A Moment in the Reeds', 0), ('A Night at the Garden', 6), ('A Nutcracker Christmas', 5), 
    ('A Prayer Before Dawn', 8), ('A Private War', 4), ('A Simple Favor', 6), ('A Star Is Born', 9), 
    ('A Sweet Christmas Romance', 1), ('A United Kingdom', 4), ('A Vigilante', 6), ("A Wizard's Tale", 5), 
    ('A Year Of British Murder', 9), ('A-X-L', 1), ('A.I. Rising', 7), ('A.M.I.', 7),
    ('Abducted in Plain Sight', 8), ('Abominable', 9), ('Action Point', 5), ('Ad Astra', 6), 
    ('Addams Family Values', 0), ('After', 4), ('After Auschwitz', 2), ('Against the Clock', 1),
    ('Against the Night', 5), ('Air Strike', 2), ('Airplane!', 5), ('Aladdin', 3), ('Albatross', 0),
    ('Alien Code', 9), ('Alien Expedition', 5), ('Alien Predator', 3), ('Alien: Containment', 5),
    ('Alita: Battle Angel', 5), ('All I Desire', 5), ('All Is True', 3), ('All the Colors of Giallo', 6), 
    ("All the Devil's Men", 5), ('Allergic Overreaction', 0), ('Always Be My Maybe', 2), ('American Animals', 2), 
    ('American Factory', 8), ('American Hangman', 3), ('American Pastoral', 4), 
    ('American Wrestler: The Wizard', 4), ('An Acceptable Loss', 5), 
    ('An Interview with God', 0), ('Anchorman 2: The Legend Continues', 1),
    ('And Then We Danced', 8), ('Andrei Rublev', 8), 
    ('André Malraux: Writer, Politician, Adventurer', 7), ('Angel Has Fallen', 9),
    ('Animal Among Us', 5), ('Animas', 3), ('Animation Outlaws', 3), ('Anna', 4), 
    ('Anna and the Apocalypse', 0), ('Annihilation', 4), ('Another Day of Life', 4),
    ('Antiporno', 3), ('Antoine Griezmann: The Making of a Legend', 9), ('Antz', 8), 
    ('Apocalypse Now', 4), ('Apollo 11', 4), ('Aquaman', 2), ('Arcadia', 7), 
    ('Arctic', 4), ('Arizona', 6), ('Asher', 6), ('Ask Dr. Ruth', 1),
    ('Assassination Nation', 0), ('Astro', 8), ("At Eternity's Gate", 2),
    ('At First Light', 8), ('At War', 8), ('At the End of the Tunnel', 8), 
    ('At the Heart of Gold: Inside the USA Gymnastics Scandal', 4), ('Atlantics', 3),
    ('Atomica', 8), ('Atone', 3), ('Attraction', 4), ('Attrition', 3), ('Autobahn', 8), 
    ('Autonomy', 3), ('Autumn Sonata', 6), ('Aux', 2), ('Avengers: Endgame', 6), 
    ('Avengers: Infinity War', 0), ('Await Further Instructions', 6), 
    ('Ayla: The Daughter of War', 5), ('BTS World Tour: Love Yourself in Seoul', 4), 
    ('Baantjer The beginning', 9), ("Babette's Feast", 7), ('Back Roads', 4), ('Backdraft', 9), 
    ('Bacurau', 5), ('Bad Honey', 9), ('Bad Times at the El Royale', 3), ('Bait', 9), 
    ('Balloon', 6), ('Batla House', 8), ('Batman', 9), ('Batman & Robin', 9), 
    ('Batman Forever', 0), ('Batman Returns', 9), ('Batman v Superman: Dawn of Justice', 2),
    ('Battle', 8), ('Battle at Big Rock', 7), ('Baywatch', 9), 
    ('Be Natural: The Untold Story of Alice Guy-Blaché', 6), ('Beast', 6), 
    ('Beautiful Boy', 9), ('Becoming Astrid', 3), ('Ben Is Back', 3), ('Bernie the Dolphin', 7), 
    ('Beyond The Sky', 8), ('Beyond White Space', 0), ('Bilal: A New Breed of Hero', 9),
    ('Bill Tilghman and the Outlaws', 8), ('Billionaire Boys Club', 8), ('Birthday', 5), ('Bit', 0), 
    ('BlacKkKlansman', 4), ("Black '47", 2), ('Black Fox', 9), ('Black Hawk Down', 2), ('Black Hole Hunters', 5),
    ('Black Swan', 5), ('Black and Blue', 1), ('Blaze', 9), ('Blind', 6), ('Bliss', 9), ('Blockers', 8),
    ('Blood Cove', 8), ('Blood Father', 9), ('Blood Quantum', 5), ('Blood Simple', 3), ('Bloody Marie', 5), 
    ('Blue Iguana', 6), ('Blue My Mind', 8), ('Boar', 1), ('Bohemian Rhapsody', 7), ('Bolden', 6), 
    ('Bolshoy', 5), ('Book of Monsters', 4), ('Booksmart', 9), ('Border', 0), ('Borderless', 0), ('Boy Erased', 4),
    ('Boychoir', 5), ('Boyka: Undisputed IV', 1), ('Brawl in Cell Block 99', 3), ('Breaking Barbi', 0),
    ('Breaking the Waves', 5), ('Breakthrough', 4), ('Breath', 9), ('Brightburn', 6), 
    ('Bring Me the Head of Alfredo Garcia', 5), ('Broken Line North', 1), ('Buffalo Boys', 8),
    ('Bumblebee', 9), ('Burn', 8), ('Burning', 8), ('Buñuel in the Labyrinth of the Turtles', 7), 
    ('Camilo sinfónico: vivir así', 7), ('Can You Ever Forgive Me?', 6), ('Cannibal Vegetarian', 1),
    ('Capernaum', 7), ('Captain America: Civil War', 2), ('Captain Marvel', 9), ('Captive State', 9), 
    ('Carrie', 9), ('Cat Sick Blues Sick Blues', 5), ('Cats', 1), ('Cencoroll Connect', 0),
    ('Central Intelligence', 9), ('Champions', 6), ('Chappie', 1), ('Char Man', 4), ('Chasing Einstein', 9), 
    ('Chicken Run', 3), ("Child's Play", 8), ('Chowchilla', 3), ('Christmas Scavenger Hunt', 0),
    ('Christmas at Graceland', 9), ('Christopher Robin', 9), ('Chuck Hank and the San Diego Twins', 7), 
    ('Chuck Norris vs Communism', 9), ('Cigarette Soup', 8), ('Cinderella and the Secret Prince', 8),
    ('Cinderella the Cat', 3), ('City of Lies', 4), ('Class Reunion', 9), ('Climate Change: The Facts', 9),
    ('Climax', 4), ('Close', 4), ('Clown Motel: Spirits Arise', 3), ('Code 8', 6), ('Cold Blood', 0),
    ('Cold Case Hammarskjöld', 6), ('Cold Pursuit', 3), ('Cold Skin', 2), ('Color Out of Space', 0), 
    ('Come and See', 2), ('Consequences', 8), ('Corporate Animals', 9), ('Countdown', 1), ('Crawl', 5),
    ('Crazy Rich Asians', 1), ('Creed II', 0), ('Crimson Peak', 8), ('Critters Attack!', 1),
    ('Crossbreed', 3), ('Crown Vic', 5), ('Crucible of the Vampire', 5), ('Cruise', 3), ('Crypto', 6),
    ('Cubby', 8), ('Culture Shock', 0), ('Custody', 8), ('Cyrano, My Love', 3), ('Damsel', 4),
    ('Dancer in the Dark', 6), ('Danger One', 3), ("Daniel Isn't Real", 1), ('Daphne', 8), 
    ('Dark Crimes', 4), ('Dark Glamour: The Blood and Guts of Hammer Productions', 7), 
    ('Dark Phoenix', 4), ('Dark Waters', 4), ('Darker than Night', 8), ('Daughter of Mine', 6),
    ('Dead Ant', 8), ('Dead Squad: Temple of the Undead', 1), ('Dead Within', 0), 
    ('Death Kiss', 1), ('Deep', 7), ('Deep Murder', 1), ('Deep Red', 8), ('Deepwater Horizon', 9), 
    ('Defective', 1), ('Demon Eye', 6), ('Demon Hole', 9), ('Desire: The Short Films of Ohm', 8),
    ('Despicable Me 3', 8), ('Despite the Falling Snow', 6), ('Destroyer', 7), 
    ('Detective Conan Zero the Enforcer', 0), ('Diane', 8), ('Diego Maradona', 9),
    ('Dirty Grandpa', 1), ('Disobedience', 8), ('Django Unchained', 8), 
    ('Doctor Sleep', 4), ('Doctor Strange', 2), ('Dogman', 3),
    ("Dogs Don't Wear Pants", 5), ('Dolemite Is My Name', 7), 
    ('Domino', 3), ('Donbass', 2), ('Donnybrook', 9), 
    ('Doom: Annihilation', 6), ('Dosed', 9), ('Double Lover', 8), ('Down', 7),
    ('Down a Dark Hall', 3), ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 2), 
    ('Dragged Across Concrete', 3), ('Dragon Ball Super: Broly', 4), ('Dragon Kingdom', 6), 
    ('Dragon Quest: Your Story', 8), ('Dredd', 4), ('Driven', 3), ('Drowning Echo', 7), ('Drunk Parents', 3),
    ('Dublin Oldschool', 5), ('Dumbo', 5), ('Dumped', 6), ("Dumplin'", 9), ('ECCO', 3), ('EXIT', 9), 
    ('Earthquake Bird', 6), ('Eat Locals', 6), ('Eighth Grade', 7), ('El Angel', 0), ('El crack cero', 3), 
    ('Elcano & Magellan: The First Voyage Around the World', 2), ('Elisa & Marcela', 8), ('Elizabeth Harvest', 3),
    ('Elliot: The Littlest Reindeer', 7), ('Eloise', 7), ('End Trip', 8), ('End of the World', 5), 
    ('Escape From Raqqa', 2), ('Escape Room', 9), ('Escaping the Madhouse: The Nellie Bly Story', 0), 
    ('Everybody Knows', 9), ('Excursion', 7), ('Expedition Amelia', 1), ('Extreme Job', 4), 
    ('Extremely Wicked, Shockingly Evil and Vile', 4), ('Extremity', 6), ('Faces Places', 7), 
    ('Fahrenheit 11/9', 2), ('Family', 9), ('Fanny and Alexander', 4), ('Fantastic Beasts and Where to Find Them', 1),
    ('Fantastic Beasts: The Crimes of Grindelwald', 2), ('Fantastic Journey to Oz', 7), ('Farmlands', 4), 
    ('Fast & Furious', 4), ('Fast & Furious Presents: Hobbs & Shaw', 6), ('Fat-Topia', 2),
    ("Fate/Stay Night: Heaven's Feel I. Presage Flower", 0), ("Fate/Stay Night: Heaven's Feel II. Lost Butterfly", 0), 
    ('Feedback', 3), ('Ferdinand', 9), ('Fidelity', 8), ('Fighter', 9), ('Fighting with My Family', 4),
    ('Final Score', 9), ('Finding Steve McQueen', 5), ('First Blood', 8), ('First Man', 6), ('Five Feet Apart', 3), 
    ('Five Fingers for Marseilles', 0), ('Flashout', 7), ('Flip That Romance', 2), ('Flushed Away', 4), 
    ('Ford v Ferrari', 4), ('Foxtrot', 3), ('Fractured', 1), ('Fragtime', 0), ('Framing John DeLorean', 3), 
    ('Fraud Saiyyan', 3), ('Freaks', 7), ('Free Solo', 9), ('Freigang', 8), ('Frenzy', 5),
    ('Friday the 13th: Vengeance', 8), ('From Atatürk to Erdoğan', 7), ('Frozen II', 1), ('Funan', 8), 
    ('Furious 7', 4), ('Galveston', 4), ('Gandhi', 4), ("Garfield's Halloween Adventure", 5), 
    ('Gary Gulman: The Great Depresh', 1), ('Gaspard at the Wedding', 9), ('Gauguin: Voyage to Tahiti', 4), 
    ('Gay Chorus Deep South', 0), ('General Commander', 8), ('General Magic', 3), ('Get Out', 5), 
    ('Get Out Your Handkerchiefs', 3), ('Ghost House', 8), ('Ghost in the Graveyard', 8), 
    ('Ghost in the Shell: Ghost Chaser', 4), ('Ghosthunter', 4), ('Ghoul', 8), ('Giant Little Ones', 8),
    ('Girl', 8), ('Girls with Balls', 8), ('Glass', 4), ('Gnome Alone', 7), ('God Bless the Broken Road', 2), 
    ('Godard Mon Amour', 6), ('Godzilla', 5), ('Godzilla: King of the Monsters', 5), ('Going Places', 5), 
    ('Going in Style', 3), ('Golden Youth', 2), ('Goldstone', 4), ('Good Boys', 8), ('Good Kisser', 0),
    ('Good Sam', 1), ('Goosebumps', 4), ('Goosebumps 2: Haunted Halloween', 2), ('Gotti', 3), 
    ('Grass is Greener', 7), ('Green Book', 5), ('Gremlins', 6), ('Grimsby', 2), 
    ('Guardians of the Galaxy', 0), ('Gully Boy', 8), ('Hagazussa', 0), 
    ('Hail Yourself, America!', 3), ('Hallowed Ground', 2), 
    ('Halloween', 7), ('Hampstead', 8), ('Happy Death Day 2U', 7),
    ('Happy End', 3), ('Hard Night Falling', 6), ('Harriet', 7),
    ('Harry Potter and the Chamber of Secrets', 8), 
    ('Hearts Beat Loud', 6), ('Heartstone', 8), ('Heavy Trip', 2),
    ('Hebe', 4), ('Hell Fest', 8), ('Hellboy', 2), ('Hellboy II: The Golden Army', 6),
    ('Her', 8), ('Her Blue Sky', 7), ('Hereditary', 8), ('Hidden Colors 5: The Art of Black Warfare', 6),
    ('Hidden Figures', 4), ('Hide in the Light', 2), ('High Energy: Disco on Amphetamines', 2), ('High Life', 6),
    ('Hoax', 3), ('Holiday', 6), ('Holmes & Watson', 8), ('Homecoming: A Film by Beyoncé', 9), ('Honey Boy', 8), 
    ('Horrible Histories: The Movie - Rotten Romans', 7), ('Hot Summer Nights', 9), ('Hotel Artemis', 4), 
    ('Hotel Mumbai', 3), ('How to Train Your Dragon: The Hidden World', 4), ('Human Nature', 2), ('Hunter Killer', 2),
    ('Hunting Lands', 8), ('Hurley', 4), ('Hustlers', 4), ('I Am Durán', 6), ('I Am Mother', 9), 
    ("I Do... Until I Don't", 6), ('I Hate Kids', 0), ('I Kill Giants', 0), ('I Lost My Body', 1),
    ('I Love My Mum', 6), ('I Remember You', 4), ('I See You', 0), ('I Spit on Your Grave: Deja Vu', 5), 
    ('I Still See You', 0), ("I'll Take Your Dead", 0), ('IO', 3), ('Ice Age: Collision Course', 4),
    ('Ice on Fire', 9), ('Icebreaker', 6), ('If Beale Street Could Talk', 4), ('Il ministro', 2),
    ('Image Makers: The Adventures of America’s Pioneer Cinematographers', 9), ('Impetigore', 0), 
    ('In Like Flynn', 4), ('In Memoriam', 8), ('In The Now', 0), ('In This Gray Place', 0), 
    ('In the Absence', 5), ('In the Fade', 2), ('In the Shadow of the Moon', 4), ('In the Tall Grass', 6), 
    ('Incredibles 2', 6), ('Indivisible', 2), ('Industrial Accident: The Story of Wax Trax! Records', 7), 
    ('Infección', 0), ('Inferno', 4), ('Inherit the Viper', 9), ('Inside Man: Most Wanted', 2), ('Insomnium', 1), 
    ('Instant Death', 6), ('Instant Family', 4), ('Into the Grand Canyon', 9), ('Iron Sky: The Coming Race', 6),
    ('Irreversible', 7), ('Island of the Hungry Ghosts', 7), ('It', 6), ('It Chapter Two', 4), ('Itzhak', 2),
    ("Ivan's Childhood", 6), ('J.T. LeRoy', 9), ('Jackie', 7), ('Jellyfish', 3), 
    ('Jin-Roh: The Wolf Brigade', 1), ('John Wick: Chapter 3 - Parabellum', 4), ('Jojo Rabbit', 2), 
    ('Joker', 2), ('Juliet, Naked', 3), ('Junglee', 1), ('Just Charlie', 8), ('Just Friends', 8), 
    ('Justified Force', 3), ('K-12', 4), ('Kaabil', 6), ('Kabaneri of the Iron Fortress: The Battle of Unato', 9),
    ('Kabir Singh', 6), ('Kamen Rider Heisei Generations FOREVER', 7), ('Karajan: Portrait of a Maestro', 7), 
    ('Karaoke Night', 5), ('Kase-san and Morning Glories', 8), ('Kasganj', 9), ('Katie Says Goodbye', 3), 
    ('Kesari', 2), ("Kiki's Delivery Service", 3), ('Killing Jesus', 9), ('Killing for the Prosecution', 1),
    ('Kim Ji-young, Born 1982', 6), ('Kim Possible', 0), ('Kin', 5), ('King Lear', 5),
    ('King of California', 8), ('King of Crime', 2), ('King of Thieves', 4), 
    ('Kishiryu Sentai Ryusoulger The Movie: Time Slip! Dinosaur Panic!!', 7), 
    ('Knives Out', 8), ('Knock Down the House', 3), ('Koko-di Koko-da', 1), ('Krrish 3', 0), 
    ('Kung Fu Panda 3', 6), ('Kursk', 9), ('La Ceremonie', 4), ('La Dolce Vita', 5), 
    ('La stagione della caccia', 4), ('Ladies in Black', 2), ("Lady Chatterley's Lover", 3),
    ('Lady Time', 8), ('Lasso', 9), ('Last Christmas', 4), ('Last Summer', 8), ('Latvian Coyote', 0),
    ('Lean on Pete', 4), ('Leave No Trace', 6), ('Lemonade', 6),
    ('Lenin, and the Other Story of the Russian Revolution', 7), 
    ('Leprechaun Returns', 0), ('Let It Snow', 8), 
    ('Let There Be Light', 4), ('Let Us Live', 7), ('Level 16', 7), ('Life Itself', 3), 
    ('Life Like', 8), ('Lifechanger', 5), ('Like a Cat on a Highway', 4), 
    ('Lindsey Vonn: The Final Season', 8), ('Little White Lies', 8), ('Little White Lies 2', 7), 
    ('Little Women', 6), ('Liz and the Blue Bird', 7), ('Lizzie', 8), ('London Fields', 4), 
    ('London Has Fallen', 9), ('Long Lost', 9), ('Long Shot', 9), ('Lords of Chaos', 2), ('Loro 1', 3),
    ('Lost Highway', 0), ('Lost in London', 7), ('Love Actually', 7), ('Low Tide', 3), ('Lowlife', 8), 
    ("Lucy Worsley's Christmas Carol Odyssey", 7), ('Lupin the Third vs. Detective Conan: The Movie', 0), 
    ('Lupin the Third: THE FIRST', 6), ('Lupin the Third: The Castle of Cagliostro', 6), ('Lying and Stealing', 1), 
    ('Léa & I', 1), ('MAL·MO·E: The Secret Mission', 4), ('MILF', 6), ('Ma', 6), ("Made in Abyss: Journey's Dawn", 0),
    ("Madeline's Madeline", 6), ('Mademoiselle Paradis', 4), ('Magellan', 6), ('Mahana', 7), ('Make Us Dream', 0), 
    ('Making Babies', 8), ('Mamma Mia! Here We Go Again', 5), ('Manaslu - Berg der Seelen', 0), ('Mandy', 2),
    ('Manhattan Night', 9), ('Manikarnika: The Queen of Jhansi', 0), ('Mapplethorpe', 7),
    ('Marcel Duchamp: The Art of the Possible', 1), ('Mari', 6), ('Maria', 4), ('Marriage Story', 6), 
    ('Marshland', 0), ("Martin's Close", 7), ('Marvel Rising: Battle of the Bands', 9),
    ('Marvel Rising: Chasing Ghosts', 9), ('Marvel Rising: Heart of Iron', 9), ('Marvel Rising: Operation Shuri', 9), 
    ('Mary Poppins Returns', 8), ('Mary Shelley', 9), ("Mary and the Witch's Flower", 4), ('Masked Mutilator', 8),
    ('Matriarch', 3), ('Maurice', 8), ('Mean Dreams', 1), ('Measure of a Man', 9), ('Mechanic: Resurrection', 6),
    ('Memoir of War', 2), ('Men in Black: International', 6), ('Mia and the White Lion', 9), ('Mickey One', 6), 
    ('Midsommar', 6), ('Midway', 2), ('Mile 22', 4), ('Miles Davis: Birth of the Cool', 2), ('Millennium Actress', 2),
    ('Minding the Gap', 6), ('Mine 9', 9), ('Mirage', 3), ('Mirai', 7), ('Miss Bala', 4), 
    ('Missing 411: The Hunted', 1), ('Missing Link', 5), ('Mom', 6), ('Mom and Dad', 3), 
    ('Money Monster', 6), ('Monstrum', 0), ('Mortal Engines', 4), ('Mortdecai', 1), ('Mother', 6), 
    ('Motherless Brooklyn', 6), ('Mrs. Rellik', 6), ('Murder Mystery', 1), ('Murder on the Orient Express', 1),
    ('My Days of Mercy', 8), ('My Hero Academia: Two Heroes', 0), ('My Neighbor Totoro', 6), 
    ('My Own Private Idaho', 8), ('My Soul To Keep', 8), ('My Tyrano: Together, Forever', 6),
    ('NJPW Royal Quest', 0), ('Naked', 1), ('Nang Nak', 2), ('Napping Princess', 6), 
    ('Naruto Shippuden the Movie: Road to Ninja', 3), ('Nefta Football Club', 9),
    ('Neon Genesis Evangelion: The End of Evangelion', 6), ('Never Grow Old', 4), ('Never Look Away', 2), ('NiNoKuni', 0), ('Night Comes On', 6), ('Night School', 5), ('Night of the Axe', 0), ('Nightmare Cinema', 0), ("Nikki Glaser: Bangin'", 1), ('No Lye: An American Beauty Story', 7), ('No Safe Spaces', 5), ("Nobody's Fool", 5), ('Nothing Like a Dame', 5), ('Notting Hill', 8), ('Now and Ever', 2), ('Nowhere to Be Found', 3), ('Occupation', 1), ('Ode to Joy', 9), ('Office Uprising', 7), ('Official Secrets', 3), ('On the Basis of Sex', 4), ('Once Upon a Time in London', 5), ('Once Upon a Time… in Hollywood', 6), ('One Winter Proposal', 9), ('Only Mine', 5), ('Only Yesterday', 9), ('Only the Brave', 8), ('Operation Mekong', 8), ('Operation Red Sea', 6), ("Ossan's Love: Love or Dead", 8), ('Our Christmas Love Song', 9), ('Out of Range', 5), ('Over the Hedge', 2), ('Overlord', 3), ('PM Narendra Modi', 3), ('Pad Man', 4), ('Padmaavat', 3), ('Pain and Glory', 6), ('Panodrama', 3), ('Papillon', 4), ('Parasite', 4), ('Paris Pigalle', 7), ('Passengers', 7), ('Patient Seven', 0), ('Patrick', 6), ('Peel', 0), ('Peppermint', 6), ('Peppermint Candy', 7), ('Perfect Skin', 7), ('Perfect Strangers', 7), ('Pet', 3), ('Pet Sematary', 6), ('Peter Pan', 6), ('Phenomena', 1), ('Pickings', 5), ('Piercing', 6), ('Place', 8), ('Play', 0), ('Play or Die', 2), ('Pledges', 1), ('Point Break', 5), ('Pokémon Detective Pikachu', 8), ('Polar', 4), ('Polaroid', 7), ('Pozole', 7), ('Prey', 9), ('Prodigy', 2), ('Professor Shanku and the El Dorado', 7), ('Prospect', 6), ('Psycho-Pass: Sinners of the System -  Case.1 Crime and Punishment', 6), ('Psycho-Pass: Sinners of the System - Case.2 First Guardian', 6), ('Purl', 1), ('Push', 2), ('Pusher', 9), ('Pusher II: With Blood on My Hands', 6), ("Pusher III: I'm the Angel of Death", 6), ('Puzzle', 8), ('Pyewacket', 8), ('QT8: The First Eight', 7), ('Quackerz', 5), ('Quarries', 9), ('Quartet', 9), ('Queen & Slim', 1), ('Quiet Storm: The Ron Artest Story', 6), ('Rabid', 8), ('Race', 5), ('Radius', 1), ('Rain, Rain, Run Away', 2), ('Raising Kratos', 2), ('Ralph Breaks the Internet', 0), ('Rambo III', 2), ('Rambo: First Blood Part II', 2), ('Rambo: Last Blood', 4), ('Ramen Shop', 6), ('Rampant', 0), ('Ranchlands', 8), ('Rascal Does Not Dream of a Dreaming Girl', 0), ('Ready or Not', 3), ('Real Cases of Shadow People: The Sarah McCormick Story', 0), ('Rebels of the Neon God', 2), ('Red Dog: True Blue', 4), ('Red Joan', 2), ('Redcon-1', 6), ('Reign of the Supermen', 7), ('Relentless', 1), ('Rent', 1), ('Replicas', 6), ('Retina', 2), ('Return to Christmas Creek', 6), ('Return to Horror Hotel', 0), ('Return to Montauk', 1), ('Revenge', 2), ('Revenger', 5), ('Ride', 0), ('Ride Your Wave', 8), ('Rio 2', 7), ('Robert Reborn', 8), ('Robin Hood', 3), ('Rock, Paper and Scissors', 5), ('Rocketman', 9), ('Rojo', 3), ('Roma', 9), ('Room for Rent', 9), ('Rootwood', 5), ("Rosemary's Baby", 4), ('Rosetta', 6), ('Running for Grace', 8), ('Running with Beto', 3), ('Russian Ark', 7), ('Rust Creek', 9), ('Ryuichi Sakamoto: Coda', 6), ('Ryuichi Sakamoto: async Live at the Park Avenue Armory', 7), ('Saaho', 8), ('Samson', 6), ('Samurai Marathon', 4), ('Santa Sangre', 0), ('Satanic Panic', 6), ('Saving Mr. Wu', 7), ('Sawah', 3), ('Scarface', 2), ('Scary Stories to Tell in the Dark', 5), ('Scheme Birds', 9), ("Schindler's List", 2), ("School's Out", 8), ('Sciences nazies', 2), ('Scream, Queen! My Nightmare on Elm Street', 6), ('Searching', 6), ('Season of Love', 0), ('Seberg', 0), ('Second Act', 3), ('Secret Santa', 0), ('Secret Superstar', 3), ('Secrets & Lies', 8), ('Self/less', 8), ('Sell By', 2), ('Serenity', 3), ('Sergio and Sergei', 3), ('Sgt. Stubby: An American Hero', 2), ('Shaft', 3), ('Shark Tale', 9), ('Shazam!', 2), ('Shed of the Dead', 2), ('Shin Godzilla', 5), ('Shoplifters', 0), ('Shut Up and Play the Piano', 7), ('Siberia', 9), ('Sibyl', 6), ('Silence', 4), ('Sinbad: Legend of the Seven Seas', 3), ('Sing', 5), ('Skate Kitchen', 6), ('Skiptrace', 5), ('Skybound', 8), ('Skyscraper', 6), ('Slasher Party', 6), ('Slaughterhouse Rulez', 4), ('Slender Man', 6), ('Slice of Life', 3), ('Slut in a Good Way', 8), ('Smallfoot', 5), ('Solaris', 7), ('Solis', 9), ('Some Time Later', 9), ('Someone Great', 6), ('Son of Saul', 2), ('Song to Song', 2), ('Sons of Denmark', 6), ('Sorry to Bother You', 0), ('Soul Hunters', 3), ('Soul to Keep', 5), ('Spider-Man: Far from Home', 6), ('Spirited Away', 8), ('Split', 6), ('Spotlight', 8), ('Spy', 2), ('Square One', 2), ('St. Agatha', 6), ('Stan & Ollie', 4), ('Stand by Me', 8), ('Stand!', 1), ('Steam Room Stories: The Movie', 8), ('Still', 3), ('Stockholm', 4), ('Stonewall', 8), ('Straight Outta Compton', 2), ('Strangerland', 4), ('Stray', 0), ('Stronger', 3), ('Submergence', 4), ('Submission', 7), ('Suicide Squad', 2), ('Summer of 84', 7), ('Summer with Monika', 3), ('Super 30', 4), ('SuperFly', 4), ('Support the Girls', 5), ('Survivor', 1), ('Suspiria', 7), ('Swedish Greasers', 6), ('Sweet Charity', 8), ('Swinging Safari', 8), ('Sword of Trust', 2), ('T-34', 2), ('Take Point', 5), ('Taxi a Gibraltar', 1), ('Tea with Mussolini', 2), ("Teddy Pendergrass: If You Don't Know Me", 8), ('Teen Titans Go! vs. Teen Titans', 7), ('Tell It to the Bees', 9), ('Terminal', 3), ('Terminator Genisys', 7), ('Terminator: Dark Fate', 4), ('Terrified', 2), ('Texas Rein', 3), ('Thank You, Eve', 9), ('That Sugar Film', 2), ('The (Silent) War', 0), ('The 12th Man', 2), ('The 5th Wave', 4), ('The Accidental Prime Minister', 3), ('The Aeronauts', 7), ('The Aftermath', 2), ('The Apollo', 7), ('The Apparition', 2), ('The Art of Racing in the Rain', 4), ('The Axiom', 2), ('The Bachelors', 3), ('The Battle: Roar to Victory', 0), ('The Best of Enemies', 4), ('The Big Bad Fox and Other Tales', 4), ('The Bird with the Crystal Plumage', 4), ('The Birdcatcher', 2), ("The Birds II: Land's End", 5), ('The Blonde One', 8), ('The Boat', 4), ('The Boogeywoman', 9), ('The Book of Life', 6), ('The Bookshop', 5), ('The Bouncer', 6), ('The Boy Who Stopped Breathing', 9), ('The Boys Are Back', 5), ('The Brave', 9), ('The Brawler', 9), ('The Breadwinner', 4), ('The Breaker Upperers', 9), ('The Bye Bye Man', 9), ('The Captain', 0), ('The Captive', 7), ('The Car: Road to Revenge', 0), ('The Cat Returns', 3), ('The Catcher Was a Spy', 2), ('The Challenger Disaster', 9), ('The Chambermaid', 3), ('The Children Act', 4), ('The Christ Slayer', 5), ('The Circus', 4), ('The Clovehitch Killer', 0), ('The Cloverfield Paradox', 0), ('The Cold Blue', 2), ("The Corporate Coup D'État", 7), ('The Counselor', 9), ('The Cranes Are Flying', 9), ('The Crucifixion', 3), ('The Danish Boys', 8), ('The Dare Project', 8), ('The Dark', 6), ('The Dark Days of Demetrius', 6), ('The Day We Walked On The Moon', 6), ('The Death & Life of John F. Donovan', 8), ('The Death of Louis XIV', 4), ('The Death of Stalin', 2), ('The Deer Hunter', 4), ('The Deminer', 1), ("The Devil's Doorway", 7), ("The Devil's Playground", 8), ('The Directive', 1), ('The Divine Order', 3), ('The Domestics', 6), ('The Earthquake', 8), ('The Elephant Man', 4), ('The Emperor of Paris', 3), ('The Endless', 2), ('The Equalizer 2', 1), ('The Fanatic', 6), ('The Farewell', 9), ('The Favourite', 4), ('The Final Wish', 7), ('The First King: Birth of an Empire', 4), ('The First Purge', 6), ('The Forgiven', 8), ('The Fortress', 9), ('The Fortune Goddess', 8), ('The Founder', 3), ('The Front Runner', 3), ('The Furies', 8), ('The Game Changers', 0), ('The Garden Left Behind', 1), ('The Gateway', 4), ('The Gift', 6), ("The Girl in the Spider's Web", 6), ('The Girl on the Train', 2), ('The Golden Glove', 4), ('The Golem', 4), ('The Goya Murders', 4), ('The Great Battle', 9), ('The Great Hack', 3), ('The Great Wall', 4), ('The Grinch', 9), ('The Gruffalo', 9), ('The Guard of Auschwitz', 2), ('The Guilty', 1), ('The Handmaiden', 0), 
    ('The Happy Prince', 4), ('The Happytime Murders', 3), ('The Harvesters', 8), ('The Haunting of La Llorona', 8), 
    ('The Heat: A Kitchen (R)evolution', 4), ('The Highwaymen', 2), ('The Hole in the Ground', 6), ('The Hollow Child', 8),
    ('The Horse Thief', 1), ('The House That Jack Built', 7), ('The House with a Clock in Its Walls', 3), 
    ('The Hunt for Jihadi John', 6), ('The Hunters', 6), ('The Hustle', 8), ('The Informer', 4), 
    ('The Intent 2: The Come Up', 2), ('The Intruder', 3), ('The Irishman', 4), ('The Isle', 5), 
    ('The Jönsson Gang in Mallorca', 7), ('The Karate Kid', 3), ('The Kid Who Would Be King', 1), 
    ('The Kindergarten Teacher', 3), ('The King', 2), ('The Last Laugh', 8), ('The Last Man', 4),
    ('The Last Survivors', 2), ('The Last Word', 4), ('The Latent Image', 8), ('The Lazarus Effect', 2),
    ('The Legend of 1900', 6), ('The Legend of Cocaine Island', 2), ('The Legend of Secret Pass', 8),
    ('The Legend of Tarzan', 5), ('The Light Between Oceans', 9), ('The Lighthouse', 7), ('The Lion King', 8),
    ('The Little Mermaid', 2), ('The Lodge', 6), ('The Lost Wife of Robert Durst', 3), 
    ('The Male Gaze: The Heat of the Night', 8), ('The Man Who Invented Christmas', 4),
    ('The Man Who Killed Hitler and Then the Bigfoot', 2), ('The Man in the Trunk', 8),
    ('The Man with the Iron Heart', 2), ('The Matrix', 6), ('The Mermaid: Lake of the Dead', 8),
    ('The Messenger', 2), ('The Midnight Man', 1), ('The Miseducation of Cameron Post', 4), 
    ('The Monster', 0), ('The Mountain', 5), ('The Mule', 4), ('The Nest', 6),
    ('The New On Cinema Oscar Special', 2), ('The New Romantic', 9), ('The Night Eats the World', 4),
    ('The Nightingale', 5), ('The Nun', 3), ('The Nutcracker and the Four Realms', 2), 
    ('The Old Man & the Gun', 3), ('The Ornament of the World', 1), ('The Pagan King', 9), 
    ('The Pass', 9), ('The Peanut Butter Falcon', 7), ('The Perfection', 2),
    ('The Photographer of Mauthausen', 2), ('The Plagiarists', 0), ('The Possession of Hannah Grace', 5),
    ('The Prayer', 9), ('The Predator', 1), ('The Prince of Egypt', 8), ('The Prodigy', 6), 
    ('The Professor', 1), ('The Professor and the Madman', 4), ('The Purity of Vengeance', 6), 
    ('The Quake', 8), ("The Queen's Corgi", 4), ('The Raft', 7), ('The Railway Man', 2), 
    ('The Realm', 3), ('The Red Sea Diving Resort', 7), ('The Reliant', 9), ('The Ring', 5), 
    ('The Ring Two', 8), ('The Rise of the Synths', 3), ('The Rising Hawk', 6), ('The River and the Wall', 0),
    ('The Royal Exchange', 7), ('The Sense of an Ending', 4), ('The Seventh Seal', 0), ('The Shining', 1), 
    ('The Shiny Shrimps', 1), ('The Shock of the Future', 7), ('The Silence', 3), ('The Silence of Others', 6),
    ('The Silent Revolution', 3), ('The Sisters Brothers', 2), ('The Souvenir', 6), ('The Spy Gone North', 4),
    ('The Spy Who Dumped Me', 7), ('The Standoff at Sparrow Creek', 6), 
    ('The Stolen Princess: Ruslan and Ludmila', 8), ('The Suicide Shop', 4), 
    ('The Swan Princess: Kingdom of Music', 2), ('The Take Down', 4), ('The Tale', 6),
    ('The Teacher', 0), ('The Tenant', 0), ('The Thing', 4), ('The Thirteenth Tale', 6), 
    ('The Tobacconist', 2), ('The Toybox', 8), ('The Traitor', 8), ('The True Adventures of Wolfboy', 6), 
    ('The Truth', 6), ('The Two Popes', 0), ('The Umbrellas of Cherbourg', 3), ('The Upside', 4),
    ('The Vanishing', 5), ('The Wandering Earth', 2), ('The Wave', 8), ('The Whale and the Raven', 0), 
    ('The White Crow', 8), ('The Wife', 3), ('The Wild Boys', 3), ('The Wild Pear Tree', 4),
    ('The Wind', 4), ('The Witch in the Window', 3), ("The Wolf's Call", 5), ('The Wonders', 8), 
    ('The Worlds of Ursula K. Le Guin', 3), ('The Writer From a Country Without Bookstores', 9),
    ('The Young Cannibals', 5), ('The Young Girls of Rochefort', 7), ('The Young Offenders', 8),
    ('The Young Victoria', 4), ('The Young and the Damned', 8), ('Then Came You', 9),
    ("There's Always Tomorrow", 9), ('They Shall Not Grow Old', 8), ("This Ain't California", 7),
    ('Three Identical Strangers', 8), ('Three Seconds', 9), ('Thriller', 5), 
    ('Tiananmen: The People Versus the Party', 6), ('Time Freak', 9), ('Time Trap', 1), 
    ('To the Ends of the World', 8), ('Together', 0), ('Togo', 4), ('Tolkien', 8), 
    ('Too Funny to Fail: The Life & Death of The Dana Carvey Show', 3), ('Top Knot Detective', 0), 
    ('Tower of Silence', 7), ('Trading Places', 3), ('Transfinite', 5), ('Transformers: The Last Knight', 5),
    ('Trapped: The Alex Cooper Story', 4), ('Trench 11', 2), ('Trial by Fire', 4), ('Trick', 8), 
    ('Trinity Seven 2: Heavens Library & Crimson Lord', 3), ('Triple Frontier', 3), ('Triple Threat', 9), 
    ('Trixie Mattel: Moving Parts', 2), ("True Justice: Bryan Stevenson's Fight for Equality", 4),
    ('Trust Machine: The Story of Blockchain', 3), ('Tucked', 6), ('Tully', 1), 
    ('Twin Murders: The Silence of the White City', 4), ('Twinsanity', 3), ('Two Tails', 8), 
    ('Tylko nie mów nikomu', 3), ('Ugetsu', 4), ('Ulan', 8), ('Unbroken: Path to Redemption', 4),
    ('Uncut Gems', 6), ('Under the Silver Lake', 2), ('Unfriended: Dark Web', 8), ('Unicorn Store', 6), 
    ('Unleashed', 4), ('Unlocked', 4), ('Unplanned', 4), ('Untouchable', 2), ('Upgrade', 9), 
    ('Uri: The Surgical Strike', 5), ('Us', 9), ('Vault', 5), ('Velvet Buzzsaw', 6), ('Venom', 8), 
    ('Verotika', 0), ('Vice', 2), ('Victor Crowley', 8), ('Vijay Superum Pournamiyum', 8), 
    ('Vikruthi', 2), ('Vision Portraits', 4), ('Vivarium', 8), ("Vive L'Amour", 9),
    ('Voice from the Stone', 8), ('Vox Lux', 9), ('Wallace & Gromit: The Curse of the Were-Rabbit', 5),
    ('War Baby', 2), ('Watchmen', 2), ('Watergate', 7), ('We Have Always Lived in the Castle', 6),
    ('We Still Steal the Old Way', 5), ('Welcome Home', 7), ('Welcome to Acapulco', 8), 
    ('Welcome to Christmas', 9), ('Welcome to Marwen', 8), ('Werewolves of the Third Reich', 2),
    ('West of Hell', 6), ('Westfalia', 0), ('What Have I Done to Deserve This?', 3), 
    ('What Keeps You Alive', 8), ('What The Durrells Did Next', 6), ('What They Had', 6),
    ('Wheely', 3), ('Where Hands Touch', 0), ('Where We Disappear', 9), ('While at War', 8),
    ('White Boy Rick', 9), ('White Fang', 9), ('White Settlers', 7), ('Whitney', 9), 
    ('Who You Think I Am', 1), ('Widows', 3), 
    ('Wild Nights with Emily', 7), ('Wild Session', 8), ('Wild Strawberries', 0), 
    ('Wildlife', 1), ('William', 0), ('Wine Country', 4), ("Winter's Blood", 4), ('Woman Walks Ahead', 4),
    ('Woodstock', 9), ('Wunderland', 2), ('Wuthering Heights', 6), ('Xenophobia', 0), ('Yardie', 4),
    ('You Were Never Really Here', 6), ('Zombieland: Double Tap', 8), 
    ('Zombies in the Sugar Cane Field. The Documentary', 7), ('Zoo', 2), ('mid90s', 0)
]